### ISSUE TITLE
[Suggestion] Simple Storage Network

### ISSUE THREAD

**Issue by vertex101** [al132mc/Down-To-Earth-Experimental#2]
it is a very lite mod uses no power and it is like a very tamed down AE system

**Comment by al132mc** [comment]
I'm a bit skeptical... I remember the mod being fairly buggy on 1.12.2 and I imagine it is even more buggy for 1.14 at this point.

**Comment by vertex101** [comment]
all the times i used the mod i never had any issues and i know new things have been added i think in 1.14.4

**Comment by al132mc** [comment]
Added to 1.10
