### ISSUE TITLE
Pearl of the Void crashes players on servers

### ISSUE THREAD

**Issue by Dr-Game** [al132mc/Down-To-Earth-Experimental#5]
*Discovered by SMERTNIK (Discord)

Wearing the Pearl of the Void spellstone from Enigmatic Legacy on your baubles will crash you from the server and will continue crashing you. The only way to fix this is to kill the player as they join so that the spellstone is removed from their baubles.

**Comment by Extegral** [comment]
The bug isn't limited to this specific modpack, actually, and was caused by Enigmatic Legacy itself.

I've fixed this in release 1.4.1.

**Comment by al132mc** [comment]
Thanks for commenting, I just updated to mod version 1.5.2 in pack version 1.11, so this should be sorted now.
